#pragma once

#include <cstdint>

enum opc_t : uint8_t {
    COPY              = 1,
    LOAD              = 2,
    STORE             = 3,
    BRANCH            = 4,
    CBRANCH           = 5,
    BRANCHIND         = 6,
    CALL              = 7,
    CALLIND           = 8,
    CALLOTHER         = 9,
    RETURN            = 10,
    INT_EQUAL         = 11,
    INT_NOTEQUAL      = 12,
    INT_SLESS         = 13,
    INT_SLESSEQUAL    = 14,
    INT_LESS          = 15,
    INT_LESSEQUAL     = 16,
    INT_ZEXT          = 17,
    INT_SEXT          = 18,
    INT_ADD           = 19,
    INT_SUB           = 20,
    INT_CARRY         = 21,
    INT_SCARRY        = 22,
    INT_SBORROW       = 23,
    INT_2COMP         = 24,
    INT_NEGATE        = 25,
    INT_XOR           = 26,
    INT_AND           = 27,
    INT_OR            = 28,
    INT_LEFT          = 29,
    INT_RIGHT         = 30,
    INT_SRIGHT        = 31,
    INT_MULT          = 32,
    INT_DIV           = 33,
    INT_SDIV          = 34,
    INT_REM           = 35,
    INT_SREM          = 36,
    BOOL_NEGATE       = 37,
    BOOL_XOR          = 38,
    BOOL_AND          = 39,
    BOOL_OR           = 40,
    FLOAT_EQUAL       = 41,
    FLOAT_NOTEQUAL    = 42,
    FLOAT_LESS        = 43,
    FLOAT_LESSEQUAL   = 44,
    FLOAT_NAN         = 46,
    FLOAT_ADD         = 47,
    FLOAT_DIV         = 48,
    FLOAT_MULT        = 49,
    FLOAT_SUB         = 50,
    FLOAT_NEG         = 51,
    FLOAT_ABS         = 52,
    FLOAT_SQRT        = 53,
    FLOAT_INT2FLOAT   = 54,
    FLOAT_FLOAT2FLOAT = 55,
    FLOAT_TRUNC       = 56,
    FLOAT_CEIL        = 57,
    FLOAT_FLOOR       = 58,
    FLOAT_ROUND       = 59,
    MULTIEQUAL        = 60,
    INDIRECT          = 61,
    PIECE             = 62,
    SUBPIECE          = 63,
    CAST              = 64,
    PTRADD            = 65,
    PTRSUB            = 66,
    SEGMENTOP         = 67,
    CPOOLREF          = 68,
    NEW               = 69,
    INSERT            = 70,
    EXTRACT           = 71,
    POPCOUNT          = 72,
};

const char *opc2str[] = {
    nullptr,
    "COPY",
    "LOAD",
    "STORE",
    "BRANCH",
    "CBRANCH",
    "BRANCHIND",
    "CALL",
    "CALLIND",
    "CALLOTHER",
    "RETURN",
    "INT_EQUAL",
    "INT_NOTEQUAL",
    "INT_SLESS",
    "INT_SLESSEQUAL",
    "INT_LESS",
    "INT_LESSEQUAL",
    "INT_ZEXT",
    "INT_SEXT",
    "INT_ADD",
    "INT_SUB",
    "INT_CARRY",
    "INT_SCARRY",
    "INT_SBORROW",
    "INT_2COMP",
    "INT_NEGATE",
    "INT_XOR",
    "INT_AND",
    "INT_OR",
    "INT_LEFT",
    "INT_RIGHT",
    "INT_SRIGHT",
    "INT_MULT",
    "INT_DIV",
    "INT_SDIV",
    "INT_REM",
    "INT_SREM",
    "BOOL_NEGATE",
    "BOOL_XOR",
    "BOOL_AND",
    "BOOL_OR",
    "FLOAT_EQUAL",
    "FLOAT_NOTEQUAL",
    "FLOAT_LESS",
    "FLOAT_LESSEQUAL",
    nullptr,
    "FLOAT_NAN",
    "FLOAT_ADD",
    "FLOAT_DIV",
    "FLOAT_MULT",
    "FLOAT_SUB",
    "FLOAT_NEG",
    "FLOAT_ABS",
    "FLOAT_SQRT",
    "FLOAT_INT2FLOAT",
    "FLOAT_FLOAT2FLOAT",
    "FLOAT_TRUNC",
    "FLOAT_CEIL",
    "FLOAT_FLOOR",
    "FLOAT_ROUND",
    "MULTIEQUAL",
    "INDIRECT",
    "PIECE",
    "SUBPIECE",
    "CAST",
    "PTRADD",
    "PTRSUB",
    "SEGMENTOP",
    "CPOOLREF",
    "NEW",
    "INSERT",
    "EXTRACT",
    "POPCOUNT",
};
